### ISSUE TITLE
parametrization

### ISSUE THREAD

**Issue by kpolszewski** [wizbii/docker-distribution-pruner#1]
great image!
could you parametrize config path and soft_delete option for better experience? right now I had to override default command

**Comment by smaftoul** [comment]
@kpolszewski are you willing to do a PR ?

**Comment by kpolszewski** [comment]
I think I might try to, not in close future, though.

**Comment by kpolszewski** [comment]
how about a merge?

**Comment by smaftoul** [comment]
Thanks for your PR  and sorry for lagging.
I'm not really satisfied with your PR for several reasons:
- you are removing the multistage build, thus the published image is bigger and ships a go toolchain
- you are adding an entrypoint with a shell script , the entrypoint could be just the pruner itself , and you can pass arguments to it on `docker run` command line
- the shell scripts sets all flags the pruner have, with all the defaults value the pruner uses. Whenever the upstream adds a flag, we need to modify the entrypoint. The same applies if the upstream changes the default value.

I regret the pruner uses the standard go flag package that doesn't allow settings flag values from environment variables.

I think, a better solution would be to write a dockerfile that starts with `FROM wizbii/docker-distribution-pruner` and just set a CMD (or an ENTRYPOINT).

I will write a README.md and submit as a PR so it's clear to everyone.
I also will create another PR to remove the `CMD ["/lib/ld-musl-x86_64.so.1",` that is strange (using `golang:alpine` as image in the first stage should be enough).

@kpolszewski what do you think ?

**Comment by kpolszewski** [comment]
Thanks for the remarks, I wasn't aware of multistage build, as it is kind of new. Definitely, all the points you've mentioned will improve usage experience of the image 👍 

closing in favor of other PRs
