### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by xanderhades** [wizbii/docker-distribution-pruner#5]
Are you still maintaining this? The docker image has not been built since 5 months ago, but the source repository seems very active.

Thanks!

**Comment by Baldinof** [comment]
Hi!

We are still using this image internally, but we don't follow upstream releases, I just triggered a new build.
Feel free to ask a build again if needed.

**Comment by xanderhades** [comment]
Hello,
thanks for the response!
It seems the build has failed.

**Comment by Baldinof** [comment]
I fixed the Dockerfile to match upstream updates, the build has succeeded :)

**Comment by xanderhades** [comment]
Thanks!
